### ISSUE TITLE
[Minor Bug] Provide List of Possible Elementary Schools to Search For

### ISSUE THREAD

**Issue by xxiaouw** [info442-spr22/f-team#56]
On the food near you page may include some guidance on possible locations to search. It would be useful for users who are not familiar with the project and possible locations to be able to explore around without background knowledge because otherwise there won't be any results shown.

**Comment by xxiaouw** [comment]
On the food near you page may include some guidance on possible locations to search. It would be useful for users who are not familiar with the project and possible locations to be able to explore around without background knowledge because otherwise there won't be any results shown.

**Comment by cmarq07** [comment]
This is a known bug by the dev team. This feature is actually available, but for some reason doesn't work on Safari or Mobile views
