### ISSUE TITLE
[Major Bug] Unable to Submit Form to Search Distance in Miles Because of Dropdown Menu

### ISSUE THREAD

**Issue by soshikun** [info442-spr22/f-team#57]
In the "Food Near You" tab: The only inputs available are the "distance in miles" text input and the checkboxes when you maneuver to that tab. I tried to search for Food Banks within 5 miles and when I clicked the "Search" button, it keeps telling me to "Fill out this field". But I can’t see the other field because the dropdown menu doesn’t go away until you click it again.

Safari on iPhone XR

Steps to Reproduce:
1. Go to site on Safari 
2. Click on the "Food Near You" option from the dropdown menu.
3. Enter "5" in the "Distance in miles" text box.
4. Uncheck "Meal" and "Community Fridge" check boxes.
5. Click "Search" button.

Expected Result: Map will display all food bank locations within 5 miles.

Actual Result: Form is unable to be submit and "Fill out this field" pop-up keeps showing up instead because the dropdown menu doesn’t go away. No markers are shown on map.

**Comment by Jaehoon01** [comment]
Will add description about what the Food Near You page is and that all fields are required.
