### ISSUE TITLE
[Minor Bug] Visual Design Bug at the Bottom of the Screen on Form Page

### ISSUE THREAD

**Issue by syesil00** [info442-spr22/f-team#58]
On the form page, the colored background doesn't extend properly to the bottom of the screen. There are colored white boxes in the bottom corners of the screen.

Google Chrome Version 101.0.4951.67 (Official Build) (64-bit) on Windows 11

1920 x 1080 resolution

![Screenshot 2022-05-18 091321](https://user-images.githubusercontent.com/63033970/169091179-4115c14a-92fb-45ea-9543-e1c3715568b6.png)

**Comment by cmarq07** [comment]
Issue with Bootstrap CSS merging with our form
