### ISSUE TITLE
[Enhancement] Putting Visual Markers / Pins on the Map

### ISSUE THREAD

**Issue by syesil00** [info442-spr22/f-team#59]
On the "Food Near You" page, I am unsure how to actually interact with the app. I have searched a couple local elementary schools and I am not receiving any results. It might be helpful to have markers or pins on the map prior to searching, so that users can see options before searching, so that they don't need specific queries in order to retrieve data.

**Comment by soopark82** [comment]
Add a description of how to interact with this page. Make the markers show up after searching. (Having them show up in prior is not valid.)
