### ISSUE TITLE
[Major Bug] Searching Schools by Name Crashes the Map

### ISSUE THREAD

**Issue by stroz08** [info442-spr22/f-team#60]
Severity: Major
Summary: Cannot search schools by name
Environment: Google Chrome Version 101.0.4951.67, Windows 10
Steps to reproduce: Go to food near you, search Laurelhurst Elementary School or Laurelhurst.
Expected Result: The location of the school
Actual Result: "Sorry, we were unable to load the map. Please try again later"

**Comment by fretws** [comment]
At first, the map shows 'No matching results', then this message is covered by the error message "Sorry, we were unable to load the map. Please try again later"

**Comment by cherimarie** [comment]
Searching by name is still causing the app to crash, but in a new way.

Steps: 
1. Enter part of a valid school name, like "Greenwood", in the search box
2. See no suggestions
3. Click "enter" to submit the search

Result:
![Screen Shot 2022-06-02 at 9 21 07 PM](https://user-images.githubusercontent.com/2523812/171785661-d5278333-5403-4eb7-98ec-f2eb13658f76.png)

Expected result: 
Some search results or suggestions would display, allowing me to find the school
