### ISSUE TITLE
[Minor Bug] Refreshing Routed Pages Produces "Page Not Found" Error

### ISSUE THREAD

**Issue by GuillyGuillaume** [info442-spr22/f-team#63]
Refreshing the browser on a routed page (ie. ....netlify.app/food-near-you or ....netlify.app/form):
Expect: Page to refresh with same/similar content.
Actual: Prompted with "Page Not Found" error (shown below).

Environment: Google Chrome Version 101.0.4951.67 (Official Build) (64-bit)
![Screenshot 2022-05-18 091330](https://user-images.githubusercontent.com/62913726/169092313-07d29c33-1fc8-40d8-9510-d57241fb612d.png)

**Comment by cmarq07** [comment]
Netlify error, will fix
