### ISSUE TITLE
[Minor Bug] Form Element Does not Accept International Phone Numbers that are Longer/Shorter than U.S Numbers

### ISSUE THREAD

**Issue by avaghela-1925502** [info442-spr22/f-team#65]
Environment occurred in: Chrome on MacOs
steps to reproduce: Add option for international numbers on form
expected result: Acceptance of international phone number
actual result: Error message saying invalid number

**Comment by cherimarie** [comment]
Great catch!

**Comment by soopark82** [comment]
Invalid

**Comment by soopark82** [comment]
**Work worth doing, will be completed in the next sprint**: Going to be fixed by making the regex (for filtering) to be more accommodating.
