### ISSUE TITLE
[Major Bug] If there is Bad Input in Name Text Box, and the User Deletes it, the Error Stays on Screen

### ISSUE THREAD

**Issue by victorgmaciel** [info442-spr22/f-team#66]
**Bug**

**● general summary of the problem**
As user fills out the form, User cannot get rid of error on various field inputs. 

**● environment:**
Windows 11 , Chrome

**● steps to reproduce**
go to form
input a bad bame : i.e. fdf 
error pops up.

**● expected result**
ability to get rid of error by putting a valid name 

**● actual result**
error doesn't go away

**Comment by cmarq07** [comment]
This shouldn't be the case, every time you input new text in a text box it should check the constraints. You are potentially putting in a bad name (later on we could add prompts for the requirements on each form entry)

**Comment by soopark82** [comment]
**Work worth doing, will be completed in the next sprint**: Will add styling that makes the error to go away once the input is validated (at every change on the input).
