### ISSUE TITLE
[Minor Bug] Search Button Always says 'Searching'

### ISSUE THREAD

**Issue by spudists** [info442-spr22/f-team#67]
Search button continues to say 'Searching' when no results have been returned.  It leads the user to believe that it is still querying somewhere despite the fact that it is likely done.
Chrome, HP Pavilion
Go to the map page, enter parameters and hit search.  You will observe that it still says 'Searching..' on the button

**Comment by soopark82** [comment]
This can be solved by fixing Issue #60.
