### ISSUE TITLE
[Enhancement] Add Prompts/Descriptors for the Search Input Fields

### ISSUE THREAD

**Issue by mariamk-2740** [info442-spr22/f-team#69]
Though the input fields have a description inside of them, I think having a prompt outside of the input field to remind the user what they are supposed to enter in the field would be beneficial. I found myself having to think twice. Also stressing that only 'elementary' schools are allowed to be entered. 

<img width="869" alt="Screen Shot 2022-05-18 at 9 21 43 AM" src="https://user-images.githubusercontent.com/62913860/169092893-01d00c9b-518d-40be-acd6-25f192e42deb.png">

**Comment by cmarq07** [comment]
Similar to #66
