### ISSUE TITLE
[Enhancement] Making the Magnify-Glass Icon on the Search Bar Clickable 

### ISSUE THREAD

**Issue by xxiaouw** [info442-spr22/f-team#75]
I would be nice to have the magnify-glass icon on the search bar clickable. It might be useful to make a smoother user experience since users may think it should be click able.

**Comment by cmarq07** [comment]
Icon should appear when there's placeholder text and if a user is typing, it should disappear

**Comment by pranavshekar** [comment]
Work worth doing, won’t be completed in the next sprint: if there's time for this to be completed, it's a great implementation
