### ISSUE TITLE
[Minor Bug] Food Resource Submission Form Doesn't Allow one Letter First Names with Full Last Names

### ISSUE THREAD

**Issue by abequette99** [info442-spr22/f-team#77]
Description: On the Food Resource Submission Form I was trying to put a name that only had one letter for the first name but a full last name but it would say invalid name on the form. Names are getting very unique these days and some people may only have a one letter name. 

Environment: Chrome Version 101.0.4951.67 

Steps: 
1. Go to forms page
2. Go to full name field
3. Type in a name that has only one letter as a first name and a full last name
4. View results that it is invalid name 

Expected results: Would not get an error message saying invalid name

Actual Results: Got an invalid name popup

**Comment by cmarq07** [comment]
Don't know why you would have a 1 letter first name with a full last name so the functionality is intended. Similar to #66 though, will add prompts with more descriptions on what needs to be inputted.
