### ISSUE TITLE
BUG, Minor: Form does not submit

### ISSUE THREAD

**Issue by RachelChung2020** [info442-spr22/f-team#78]
After filling out the information correctly and hitting the submit button, nothing happens. I'm not sure if this was intentional or not though. 

**Environment it was encountered in:** Chrome v101.0.4951.67 in Windows

**Steps to reproduce:**
1. Fill out required information in the form
2. Click submit button

**Expected result:** a confirmation page

**Actual result:**: same page, no update

**Comment by xxiaouw** [comment]
additional information: the information that the user inputted in the form would still remain in the form (does not disappear)

**Comment by cherimarie** [comment]
This is a UI bug. The form does submit, but there's no user feedback to show it was successful. It's "minor".
