### ISSUE TITLE
[Enhancement] The Submission Form for the Phone Number Section, Add a Pop-Up Warning Message for not Matching the Format

### ISSUE THREAD

**Issue by xxiaouw** [info442-spr22/f-team#79]
On the form page, the "your phone" section is required. When you enter a phone number like 2067926091, it would not show any warnings, but when you hit submit, it will say "please match the requested format". I would be helpful to show pop up right after I enter the phone number so I can know to change it before submitting it. Because user would expect no error if there is no popup warnings

**Comment by cmarq07** [comment]
Similar to #66
