### ISSUE TITLE
[Enhancement] Clear out the filter below the search bar

### ISSUE THREAD

**Issue by MARY4177** [info442-spr22/f-team#83]
Most of the websites initially don't have filters filled out before users customize them themselves, so having those filters (checkmarks) filled out before the searching may limit the opportunities for users to look for certain locations. And they would not easily think that they had to mark or unmark it because it's prefilled and people naturally think it's unchecked.
![image](https://user-images.githubusercontent.com/55933930/169104544-4c3c63ff-fe5e-4cd4-95c4-8e1fb7ed660f.png)

**Comment by pranavshekar** [comment]
Not applicable to our scope
