### ISSUE TITLE
[Enhancement] Cannot Type Hyphens in Name

### ISSUE THREAD

**Issue by alanytran** [info442-spr22/f-team#84]
For the resource area, hyphens are not allowed to be put in. It returns with a bad name error message
Chrome v90.0.4430.85 on macOS Montery
probably an if statement will fix this issue
I would expect it to work with hyphens

**Comment by cmarq07** [comment]
Intended functionality as of now, current error validation on form page is very minimal

**Comment by soopark82** [comment]
Work worth doing, will be completed in the next sprint: Modify regex that accommodates the hyphen
